### ISSUE TITLE
MVP AI user tasks

### ISSUE THREAD

**Issue by tahpot** [verida/data-connector-server#95]
- [x] Gmail: Support a variation of ItemsRangeTracker which tracks page positions to ensure new emails are fetched before old emails
- [x] Gmail: Ensure sent items are included
- [x] Handle sync timeouts
- [x] Handle sync errors
- [x] Neatly handle not having permission for a handler
- [x] Start syncing items after connection established
- [x] Support sync scheduling
- [x] Sync handlers in parallel
- [x] New sync data needs to update cached index
- [x] Support populating Telegram avatar
- [x] Support populating Google avatar
- [x] Add common test - backfill complete (see @todo)
- [x] ~Extract `replyBody` from emails~ https://github.com/verida/data-connector-server/issues/127
- [x] ~Support "refetch all" option for handlers~ See https://github.com/verida/data-connector-server/issues/125
- [x] ~Support protocol compaction, enable regularly for connections schema and social/chat schema~ https://github.com/verida/data-connector-server/issues/126

**Comment by tahpot** [comment]
Pre-alpha:

- [ ] Update database `total` as per aurel request
- [ ] New sync data needs to update cached index
- [ ] Gmail: Ensure sent items are included
- [ ] Start syncing items after connection established
- [ ] Support restricting how many items to fetch based on options
- [ ] Update config so sync does a lot at the start
- [ ] Setup production ready connections with each third party
- [ ] Setup mainnet alpha config file
- [ ] Deploy to marlin oyster

Alpha:

- [ ] Google Calendar
- [ ] Slack
- [ ] Whitelist DIDs for access
- [ ] Fix sync scheduling management

**Comment by tahpot** [comment]
Suport token expiry and access denied:

- [x] Google (excl. calendar)
- [ ] Telegram
- [ ] Slack
- [ ] Facebook
- [ ] Discord

**Comment by tahpot** [comment]
Unit tests:

- [ ] Sync management
